---
# Red Hat Delivery Specialist - Ansible Advanced
# Homework Assignment
# Provision 3-Tier-App on OSP instances

- name: QA Environment - 3-Tier Apps Deployments through Openstack instances
  hosts: workstation-3847.rhpds.opentlc.com
  vars:
    - cloud_name: ospcloud
    - region_name: RegionOne
  gather_facts: true
  roles:
    - osp-facts
    # - 3tier-frontend
    # - 3tier-app
    # - 3tier-appdb
    # - 3tier-smoketest

# Frontends Tier
- name: Deploy FrontEnd Servers
  hosts: frontends
  become: yes
  gather_facts: false
  roles:
    - 3tier-repo
    - 3tier-frontend

# Apps Tier
- name: Deploy Application Servers
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - 3tier-repo
    - 3tier-app

#
# # Appdbs Tier
# - name: Deploy Database Servers
#   become: yes
#   hosts: appdbs
#   roles:
#     - {name: 3tier-repo, tags: check-repo}
#     - {name: 3tier-appdb, tags: deploy-appdb}
#
# - name: Smoketest 1 on Frontend Servers
#   hosts: frontends
#   become: no
#   tasks:
#   - uri:
#       url: http://localhost
#       return_content: yes
#     register: webpage
#
# - name: Smoketest 2 on Frontend Servers
#   hosts: frontends
#   become: no
#   tasks:
#   - uri:
#       url: http://localhost
#       return_content: yes
#     register: webpage
#
# - name: Smoketest 3 on Frontend Servers
#   hosts: frontends
#   become: no
#   tasks:
#   - uri:
#       url: http://localhost
#       return_content: yes
#     register: webpage

...
