---
# Red Hat Delivery Specialist - Ansible Advanced
# Homework Assignment
# Provision Production Environment on AWS

- name: Production Environment - AWS Infrastructure Deployment through a Jumpbox
  # Requirements: Jumpbox is already configured
  hosts: workstation-3847.rhpds.opentlc.com
  # Provision Openstack Network/Security/Instances using multiple variables
  gather_facts: false
  become: yes
  become_method: sudo
  tasks:
  - name: Extend PATH to include /home/cloud-user/bin
    shell: PATH=$PATH:/home/cloud-user/bin
  - name: Provision AWS via script
    shell: source ./credential.rc ; ./order_svc.sh -c 'OPENTLC Automation' -i 'Three Tier Application' -t 1 -y
    args:
      chdir: /home/cloud-user
    #environment:
    #  PATH:$PATH:/home/cloud-user/bin
    register: aws_result

  - debug: var=aws_result

...
