---
# Red Hat Delivery Specialist - Ansible Advanced
# Homework Assignment
# Provision QA Environment on Openstack

- name: OpenStack Deployment through a Jumpbox
  # Requirements: Jumpbox is already configured
  hosts: workstation-3847.rhpds.opentlc.com
  vars_files:
    - osp_network_var.yml
  vars:
    cloud_name: ospcloud
  roles:
    - osp-network
...
