---
# Red Hat Delivery Specialist - Ansible Advanced
# Homework Assignment
# Provision Production Environment on AWS

- name: Production Environment - AWS Infrastructure Deployment through a Jumpbox
  # Requirements: Jumpbox is already configured
  hosts: workstation-3847.rhpds.opentlc.com
  # Provision Openstack Network/Security/Instances using multiple variables
  # ansible_env must be gathered from facts, thus gathering facts can't be disabled
  gather_facts: true
  become: yes
  become_method: sudo
  tasks:
  - name: Provision AWS via script order_svc
    shell: source ./credential.rc ; ./order_svc.sh -c 'OPENTLC Automation' -i 'Three Tier Application' -t 1 -y
    args:
      chdir: /home/cloud-user
    # Since jq command will be called from /home/cloud-user/bin, we need to expand the PATH
    environment:
      PATH: "{{ ansible_env.PATH }}:/home/cloud-user/bin"
    register: aws_result

  - debug: var=aws_result

...
