---
# Red Hat Delivery Specialist - Ansible Advanced
# Homework Assignment
# Provision QA Environment on Openstack

- name: OpenStack Deployment through a Jumpbox
  # Requirements: Jumpbox is already configured
  # Jumpbox enables ssh forward via ~/.ssh/config of the cloud-user
  hosts: workstation-3847.rhpds.opentlc.com
  vars_files:
    - vars/osp_network.yml
  vars:
    cloud_name: ospcloud
  roles:
    - osp-network
...
