---
# Red Hat Delivery Specialist - Ansible Advanced
# Homework Assignment
# Provision QA Environment on Openstack

- name: QA Environment - OpenStack Deployment through a Jumpbox
  # Requirements: Jumpbox is already configured
  # Jumpbox enables ssh forward via ~/.ssh/config of the cloud-user
  hosts: workstation-3847.rhpds.opentlc.com
  # Provision Openstack Network/Security/Instances using multiple variables
  vars_files:
    - vars/osp_network.yml
    - vars/osp_securitygroup.yml
    - vars/osp_flavor.yml
    - vars/osp_instances.yml
  vars:
    cloud_name: ospcloud
  roles:
    - osp-network
    - osp-keypair
    - osp-securitygroup
    - osp-flavor
  # Create Server Instances
    - {name: osp-instances, target_instance: '{{ instance_frontend1 }}'}
    - {name: osp-instances, target_instance: '{{ instance_app1 }}'}
    - {name: osp-instances, target_instance: '{{ instance_app2 }}'}
    - {name: osp-instances, target_instance: '{{ instance_db }}'}

...
