---
# We are going to use 2 layer arrays from vars/osp_securitygroup
# Using with_subelements
- debug: var=securitygroup

- name: Create OpenStack Security Group
  os_security_group:
    cloud: "{{ cloud_name }}"
    state: present
    name: "{{ item.name }}"
    description: ports_open
  with_items:
      - "{{ securitygroup }}"
  register: result_group
  tags:
    - osp-securitygroup

- debug: var=result_group
  tags:
    - osp-securitygroup

- name: Create OpenStack Security Group Rules
  os_security_group_rule:
    cloud: "{{ cloud_name }}"
    security_group: "{{ item.0.name }}"
    protocol: "{{ item.0.protocol }}"
    port_range_min: "{{ item.1.port }}"
    port_range_max: "{{ item.1.port }}"
    remote_ip_prefix: "{{ item.1.ip_prefix }}"
  with_subelements:
    - "{{ securitygroup }}"
    - rule
  register: result_rule
  tags:
    - osp-securitygroup

- debug: var=result_rule
  tags:
    - osp-securitygroup

...
