---
# We are going to use 2 layer arrays from vars/osp_securitygroup
- debug: var=securitygroup

- os_security_group:
    cloud: "{{ cloud_name }}"
    state: present
    name: "{{ item.name }}"
    description: ports_open
    with_items:
      - "{{ securitygroup }}"
    register: result_group

- debug: var=result_group

- os_security_group_rule:
    cloud: "{{ cloud_name }}"
    security_group: "{{ item.0.name }}"
    protocol: "{{ item.0.protocol }}"
    port_range_min: "{{ item.1.port }}"
    port_range_max: "{{ item.1.port }}"
    remote_ip_prefix: "{{ item.1.ip_prefix }}"
  with_subelements:
    - "{{ securitygroup }}"
    - rule
  register: result_rule

- debug: var=result_rule
...
