---
# Gathering Facts for In-Memory Inventory for Openstack Instances

- name: Gather Openstack instances facts
  check_mode: no
  os_server_facts:
    cloud: "{{ cloud_name }}"
    region_name: "{{ region_name }}"
  register: result
  tags:
    - osp-facts

- name: Creating Dynamic Inventory - Group
  check_mode: no
  add_host:
    name: "{{ item.public_v4 }}"
    group: "{{ item.metadata.group }}"
    # ansible_ssh_private_key_file: ~/.ssh/openstack.pem
    # ansible_ssh_user: cloud-user
  with_items: "{{result.ansible_facts.openstack_servers}}"
  tags:
    - osp-facts

- name: Creating Dynamic Inventory - Deployment Group
  check_mode: no
  add_host:
    name: "{{ item.public_v4 }}"
    group: "{{ item.metadata.deployment_name }}"
    #  ansible_ssh_private_key_file: ~/.ssh/openstack.pem
    #  ansible_ssh_user: cloud-user
  with_items: "{{result.ansible_facts.openstack_servers}}"
  tags:
    - osp-facts  

...
