---
# Smoke Test for the Fronetend Servers
# We do it 3 times to observe load-balancing HAProxh in os_server_action

- name: Smoketest 1 on Frontend Servers
  hosts: frontends
  become: no
  tasks:
  - uri:
      url: http://localhost
      return_content: yes
    register: webpage

#- debug: var=webpage

- name: Smoketest 2 on Frontend Servers
  hosts: frontends
  become: no
  tasks:
  - uri:
      url: http://localhost
      return_content: yes
    register: webpage

#- debug: var=webpage

- name: Smoketest 3 on Frontend Servers
  hosts: frontends
  become: no
  tasks:
  - uri:
      url: http://localhost
      return_content: yes
    register: webpage

#- debug: var=webpage

...
