---
# Generate SSH Keys for Jumpbox to connect to Openstack

- name: Generate local key files on Jumpbox
  user:
    name: "{{ ansible_env.USER }}"
    generate_ssh_key: yes
    ssh_key_file: .ssh/test_id_rsa
  tags:
    - osp-keypair
    - osp-keypair-reinstall

# Use this when we are changing key as hash will be different
- name: Delete Keys on Openstack
  os_keypair:
    cloud: "{{ cloud_name }}"
    state: absent
    name: ansible_ssh
  tags:
   - osp-keypair-reinstall

- name: Install Key on Openstack
  os_keypair:
    cloud: "{{ cloud_name }}"
    state: present
    name: ansible_ssh
    public_key_file: "{{ ansible_env.HOME }}/.ssh/test_id_rsa.pub"
  tags:
    - osp-keypair
    - osp-keypair-reinstall
...
